import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'bg' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  bg: {
    // Header
    'header.title': 'AIPHARM+',
    'header.subtitle': 'AI аптека и асистент',
    'header.search': 'Търсете лекарства, витамини, козметика...',
    'header.phone': '+359 2 123 4567',
    'header.freeDelivery': 'Безплатна доставка над €25',
    'header.myProfile': 'Моят профил',
    'header.help': 'Помощ',
    'header.login': 'Вход',
    'header.register': 'Регистрация',
    'header.logout': 'Изход',
    'header.settings': 'Настройки на профила',
    'header.adminPanel': 'Админ панел',
    'header.hello': 'Здравейте',
    'header.administrator': 'Администратор',

    // Navigation
    'navigation.categories': 'Категории',
    'navigation.products': 'Продукти',

    // Hero Section
    'hero.title': 'AIPHARM+',
    'hero.description': 'Качествени лекарства с AI консултации и бърза доставка',
    'hero.certifiedQuality': 'Сертифицирано качество',
    'hero.support247': '24/7 Поддръжка',
    'hero.expressDelivery': 'Експресна доставка',
    'hero.qualityAwards': 'Награди за качество',
    'hero.viewProducts': 'Разгледайте продуктите',
    'hero.aiAssistant': 'AI Медицински асистент',
    'hero.satisfiedClients': 'Доволни клиенти',
    'hero.productsInStock': 'Продукта в наличност',
    'hero.professionalCare': 'Професионална грижа',

    // Categories
    'categories.title': 'Категории',
    'categories.subtitle': 'Разгледайте нашите основни категории и открийте подходящите продукти.',
    'categories.previewSubtitle': 'Бърз поглед към някои от най-популярните ни категории.',
    'categories.viewAll': 'Виж всички категории',
    'categories.viewProducts': 'Виж продуктите',
    'categories.all': 'Всички',
    'categories.painkillers': 'Обезболяващи',
    'categories.vitamins': 'Витамини',
    'categories.coldFlu': 'Простуда и грип',
    'categories.digestive': 'Стомашно-чревни',
    'categories.skinHair': 'Кожа и коса',
    'categories.children': 'Детски продукти',

    // Products
    'products.featuredTitle': 'Акцентирани продукти',
    'products.featuredSubtitle': 'Показваме селекция от най-търсените ни предложения.',
    'products.resultsFor': 'Резултати за',
    'products.category': 'Категория',
    'products.unknown': 'Неизвестна',
    'products.allProducts': 'Всички продукти',
    'products.products': 'продукта',
    'products.noProducts': 'Няма намерени продукти',
    'products.tryDifferent': 'Опитайте с различни ключови думи или разгледайте нашите категории',
    'products.viewAll': 'Разгледайте всички продукти',
    'products.showLess': 'Покажи по-малко',
    'products.prescription': 'Рецепта',
    'products.activeIngredient': 'Активна съставка',
    'products.dosage': 'Дозировка',
    'products.manufacturer': 'Производител',
    'products.inStock': 'В наличност',
    'products.outOfStock': 'Няма в наличност',
    'products.pieces': 'бр.',
    'products.add': 'Добави',
    'products.catalogTitle': 'Каталог продукти',
    'products.catalogDescription': 'Разгледайте пълната гама от лекарства, добавки и козметика, подбрани от нашите специалисти.',
    'products.categoryOverview': 'Категории и наличности',
    'products.categoryOverviewDescription': 'Бърз поглед върху основните ни категории и налични продукти.',
    'products.totalProductsLabel': 'Общо продукти',
    'products.inCategory': 'В категорията',

    // Cart
    'cart.title': 'Количка',
    'cart.empty': 'Количката е празна',
    'cart.emptyDescription': 'Добавете продукти, за да продължите с поръчката',
    'cart.continueShopping': 'Продължете пазаруването',
    'cart.remove': 'Премахни',
    'cart.total': 'Общо',
    'cart.freeDelivery': '✓ Безплатна доставка',
    'cart.addForFreeDelivery': 'Добавете продукти за €{amount} за безплатна доставка',
    'cart.checkout': 'Финализиране на поръчка',

    // AI Assistant
    'ai.title': 'AI Асистент',
    'ai.subtitle': 'Винаги готов да помогне',
    'ai.placeholder': 'Задайте въпрос за лекарство...',
    'ai.thinking': 'Обмислям отговора...',
    'ai.disclaimer': '⚠️ Това е общa информация. Консултирайте се с лекар.',
    'ai.quickQuestion1': 'Как се взима парацетамол?',
    'ai.quickQuestion2': 'Странични ефекти на ибупрофен?',
    'ai.quickQuestion3': 'Витамин C дозировка?',

    // Auth
    'auth.login': 'Вход',
    'auth.loginSubtitle': 'Влезте в профила си',
    'auth.register': 'Регистрация',
    'auth.registerSubtitle': 'Създайте нов акаунт',
    'auth.email': 'Имейл адрес',
    'auth.password': 'Парола',
    'auth.confirmPassword': 'Потвърдете паролата',
    'auth.fullName': 'Пълно име',
    'auth.firstName': 'Име',
    'auth.lastName': 'Фамилия',
    'auth.phone': 'Телефон',
    'auth.address': 'Адрес',
    'auth.age': 'Години',
    'auth.gender': 'Пол',
    'auth.male': 'Мъж',
    'auth.female': 'Жена',
    'auth.other': 'Друг',
    'auth.rememberMe': 'Запомни ме',
    'auth.forgotPassword': 'Забравена парола?',
    'auth.loginButton': 'Влез',
    'auth.registerButton': 'Регистрирай се',
    'auth.loggingIn': 'Влизане...',
    'auth.registering': 'Регистриране...',
    'auth.noAccount': 'Нямате акаунт?',
    'auth.haveAccount': 'Вече имате акаунт?',
    'auth.loginHere': 'Влезте тук',
    'auth.registerHere': 'Регистрирайте се',
    'auth.demoAccounts': 'Демо акаунти:',
    'auth.admin': 'Админ',
    'auth.user': 'Потребител',
    'auth.required': 'Задължително поле',
    'auth.passwordsNotMatch': 'Паролите не съвпадат',
    'auth.loginError': 'Грешка при вход',
    'auth.registerError': 'Грешка при регистрация',
    'auth.networkError': 'Мрежова грешка',
    'auth.loginSuccess': 'Успешен вход',
    'auth.registerSuccess': 'Регистрацията е успешна! Можете да влезете в профила си.',

    // Profile Settings
    'profile.title': 'Настройки на профила',
    'profile.subtitle': 'Актуализирайте своята основна информация и контакти.',
    'profile.email': 'Имейл адрес',
    'profile.readonlyEmail': 'Имейл адресът не може да бъде променян.',
    'profile.adminBadge': 'Администратор',
    'profile.fullName': 'Пълно име',
    'profile.fullNamePlaceholder': 'Иван Иванов',
    'profile.phoneNumber': 'Телефон',
    'profile.phonePlaceholder': '+359 88 123 4567',
    'profile.address': 'Адрес',
    'profile.addressPlaceholder': 'гр. София, ул. „Пример“ 1',
    'profile.reset': 'Възстанови',
    'profile.save': 'Запази промените',
    'profile.saving': 'Запазване...',
    'profile.success': 'Профилът беше обновен успешно.',
    'profile.error': 'Възникна грешка при обновяване на профила.',
    'profile.notAuthenticated': 'За да редактирате профила си, трябва да влезете.',

    // Admin Panel
    'admin.panel.title': 'Администраторски панел',
    'admin.panel.subtitle': 'Управлявайте потребителите и техните права',
    'admin.panel.description': 'Вижте списъка с потребители, редактирайте данни и контролирайте достъпа до платформата.',
    'admin.users.searchLabel': 'Търсене на потребители',
    'admin.users.searchPlaceholder': 'Име, имейл или телефон...',
    'admin.users.errors.noSession': 'Не е намерен валиден админ токен. Влезте отново.',
    'admin.users.errors.fetchFailed': 'Неуспешно зареждане на потребителите.',
    'admin.users.errors.saveFailed': 'Неуспешно запазване на промените.',
    'admin.users.retry': 'Опитайте отново',
    'admin.users.badges.admin': 'Администратор',
    'admin.users.badges.deactivated': 'Деактивиран',
    'admin.users.badges.active': 'Активен',
    'admin.users.empty': 'Няма намерени потребители.',
    'admin.users.unknownName': 'Няма име',
    'admin.users.memberSince': 'Член от {date}',
    'admin.users.saveSuccess': 'Потребителят е обновен успешно.',
    'admin.users.permissions.title': 'Права и статус',
    'admin.users.permissions.admin': 'Администраторски права',
    'admin.users.permissions.deactivate': 'Маркирай като деактивиран',
    'admin.users.permissions.selfWarning': 'Внимание: променяте собствения си акаунт. Не премахвайте администраторските права, ако се нуждаете от достъп.',
    'admin.users.fields.email': 'Имейл',
    'admin.users.fields.fullName': 'Пълно име',
    'admin.users.fields.fullNamePlaceholder': 'Име и фамилия',
    'admin.users.fields.phone': 'Телефон',
    'admin.users.fields.phonePlaceholder': 'Мобилен телефон',
    'admin.users.fields.address': 'Адрес',
    'admin.users.fields.addressPlaceholder': 'Адрес за доставка',
    'admin.users.actions.reset': 'Отмени промените',
    'admin.users.actions.refresh': 'Презареди',
    'admin.users.actions.saving': 'Запазване...',
    'admin.users.actions.save': 'Запази',
    'admin.users.noSelection': 'Изберете потребител от списъка, за да редактирате неговите данни.',
    // Footer
    'footer.title': 'AIPHARM+',
    'footer.description': 'Качествени лекарства с AI консултации и бърза доставка.',
    'footer.quickLinks': 'Бързи връзки',
    'footer.aboutUs': 'За нас',
    'footer.products': 'Продукти',
    'footer.services': 'Услуги',
    'footer.contacts': 'Контакти',
    'footer.promotions': 'Промоции',
    'footer.faq': 'Често задавани въпроси',
    'footer.contactsTitle': 'Контакти',
    'footer.workingHours': 'Работно време',
    'footer.workingHoursText': 'Пон-Пет: 8:00 - 22:00\nСъб-Нед: 9:00 - 20:00',
    'footer.copyright': '© 2024 AIPHARM+. Всички права запазени.',
    'footer.privacy': 'Политика за поверителност',
    'footer.terms': 'Условия за ползване',
    'footer.cookies': 'Бисквитки',

    // Common
    'common.loading': 'Зареждане...',
    'common.error': 'Грешка',
    'common.success': 'Успех',
    'common.cancel': 'Отказ',
    'common.save': 'Запази',
    'common.delete': 'Изтрий',
    'common.edit': 'Редактирай',
    'common.close': 'Затвори',
    'common.back': 'Назад',
    'common.next': 'Напред',
    'common.previous': 'Предишна',
    'common.search': 'Търсене',
    'common.filter': 'Филтър',
    'common.sort': 'Сортиране',
    'common.price': 'Цена',
    'common.quantity': 'Количество',
    'common.total': 'Общо',
    'common.currency': '€',

    // About Us
    'about.description': 'AIPHARM+ е водеща дигитална аптека в България, която съчетава традиционната фармацевтична грижа с най-новите AI технологии.',
    'about.mission': 'Нашата мисия',
    'about.missionText': 'Да предоставяме качествени лекарства и здравни продукти с персонализирани AI консултации, осигурявайки достъпна и надеждна здравна грижа за всеки.',
    'about.vision': 'Нашата визия',
    'about.visionText': 'Да бъдем най-доверената дигитална аптека в България, революционизирайки начина, по който хората получават медицински съвети и лекарства.',
    'about.quality': 'Качество',
    'about.qualityText': 'Всички наши продукти са сертифицирани и одобрени от БЛС.',
    'about.speed': 'Бързина',
    'about.speedText': 'Експресна доставка до 2 часа в София и до 24 часа в цялата страна.',
    'about.care': 'Грижа',
    'about.careText': '24/7 AI асистент и професионални фармацевти на ваше разположение.',
    'about.clients': 'Доволни клиенти',
    'about.products': 'Продукта в наличност',
    'about.experience': 'Години опит',
    'about.support': 'Поддръжка',

    // Services
    'services.pageTitle': 'Нашите услуги',
    'services.pageDescription': 'Комбинираме дигитални иновации с професионална фармацевтична грижа.',
    'services.aiConsultationsTitle': 'AI здравни консултации',
    'services.aiConsultationsDescription': 'Виртуален асистент предоставя доказателствени препоръки и проследява вашите симптоми.',
    'services.aiConsultationsFeature1': 'Персонализирани препоръки за лекарства',
    'services.aiConsultationsFeature2': 'Анализ на симптоми в реално време',
    'services.aiConsultationsFeature3': 'Ескалация към фармацевт при нужда',
    'services.telepharmacyTitle': 'Телефармация с експерти',
    'services.telepharmacyDescription': 'Лицензирани фармацевти, които ви подкрепят дистанционно.',
    'services.telepharmacyFeature1': 'Видео консултации и чат на живо',
    'services.telepharmacyFeature2': 'Проверка за взаимодействия на лекарства',
    'services.telepharmacyFeature3': 'Проследяване на терапиите и контролни обаждания',
    'services.deliveryTitle': 'Логистика и доставка',
    'services.deliveryDescription': 'Собствена мрежа за бърза и сигурна доставка в цялата страна.',
    'services.deliveryFeature1': 'Експресни доставки до 2 часа в София',
    'services.deliveryFeature2': 'Проследяване на пратката в реално време',
    'services.deliveryFeature3': 'Температурно контролиран транспорт',
    'services.valueTitle': 'Защо да изберете AIPHARM+',
    'services.valueSubtitle': 'Съчетаваме безопасност, експертиза и удобство за нашите клиенти.',
    'services.valuePatients': 'Грижа за пациента',
    'services.valuePatientsDesc': 'Индивидуални планове и напомняния за прием на лекарства.',
    'services.valueData': 'Сигурност на данните',
    'services.valueDataDesc': 'Напълно криптирана платформа с постоянен мониторинг.',
    'services.valueSupport': 'Поддръжка 24/7',
    'services.valueSupportDesc': 'Експерти на разположение по телефон, чат и имейл.',
    'services.ctaTitle': 'Нуждаете се от персонална консултация?',
    'services.ctaDescription': 'Свържете се с нас и ще ви насочим към най-подходящата услуга.',
    'services.ctaButton': 'Свържете се с експерт',

    // Contacts
    'contacts.description': 'Свържете се с нас по всяко време. Нашият екип е готов да ви помогне с всички въпроси.',
    'contacts.info': 'Информация за контакт',
    'contacts.phone': 'Телефон',
    'contacts.email': 'Имейл',
    'contacts.address': 'Адрес',
    'contacts.emergency': 'Спешни случаи',
    'contacts.emergencyText': 'При медицински спешни случаи, моля обърнете се към спешните служби.',
    'contacts.emergencyNumber': 'Спешен номер',
    'contacts.sendMessage': 'Изпратете съобщение',
    'contacts.firstName': 'Име',
    'contacts.lastName': 'Фамилия',
    'contacts.subject': 'Тема',
    'contacts.message': 'Съобщение',
    'contacts.send': 'Изпрати',
    'contacts.firstNamePlaceholder': 'Вашето име',
    'contacts.lastNamePlaceholder': 'Вашата фамилия',
    'contacts.emailPlaceholder': 'your@email.com',
    'contacts.subjectPlaceholder': 'Тема на съобщението',
    'contacts.messagePlaceholder': 'Напишете вашето съобщение тук...',

    // Promotions
    'promotions.description': 'Открийте нашите актуални промоции и спестете при покупката на лекарства и здравни продукти.',
    'promotions.freeDelivery': 'Безплатна доставка',
    'promotions.freeDeliveryDesc': 'Безплатна доставка за всички поръчки над €25 в цялата страна.',
    'promotions.vitamins20': '20% отстъпка на витамини',
    'promotions.vitamins20Desc': 'Специална промоция на всички витамини и хранителни добавки.',
    'promotions.firstOrder': 'Първа поръчка',
    'promotions.firstOrderDesc': '15% отстъпка за нови клиенти при първата им поръчка.',
    'promotions.loyaltyProgram': 'Програма за лоялност',
    'promotions.loyaltyProgramDesc': 'Събирайте точки с всяка покупка и получавайте отстъпки.',
    'promotions.free': 'Безплатно',
    'promotions.points': 'Точки',
    'promotions.permanent': 'Постоянна',
    'promotions.discount': 'отстъпка',
    'promotions.validUntil': 'Валидна до',
    'promotions.useNow': 'Използвай сега',
    'promotions.howToUse': 'Как да използвате промоциите',
    'promotions.step1': 'Изберете продукти',
    'promotions.step1Desc': 'Добавете желаните продукти в количката си.',
    'promotions.step2': 'Приложете код',
    'promotions.step2Desc': 'Въведете промо кода при финализиране.',
    'promotions.step3': 'Спестете пари',
    'promotions.step3Desc': 'Получете отстъпката и завършете поръчката.',

    // FAQ
    'faq.description': 'Намерете отговори на най-често задаваните въпроси за нашите услуги.',
    'faq.searchPlaceholder': 'Търсете въпрос...',
    'faq.noResults': 'Няма намерени резултати',
    'faq.tryDifferent': 'Опитайте с различни ключови думи.',
    'faq.stillNeedHelp': 'Все още имате нужда от помощ?',
    'faq.contactSupport': 'Нашият екип за поддръжка е готов да ви помогне.',
    'faq.callUs': 'Обадете се',
    'faq.emailUs': 'Изпратете имейл',
    'faq.q1': 'Колко време отнема доставката?',
    'faq.a1': 'Доставката в София е до 2 часа, а в останалата част на страната - до 24 часа. За спешни случаи предлагаме експресна доставка.',
    'faq.q2': 'Какви методи за плащане приемате?',
    'faq.a2': 'Приемаме плащания с дебитни и кредитни карти, банков превод, както и плащане при доставка (наложен платеж).',
    'faq.q3': 'Нужна ли е рецепта за всички лекарства?',
    'faq.a3': 'Не, много лекарства са безрецептурни. Продуктите, които изискват рецепта, са ясно обозначени в сайта.',
    'faq.q4': 'Как работи AI асистентът?',
    'faq.a4': 'Нашият AI асистент предоставя обща информация за лекарствата. Винаги се консултирайте с лекар за персонализиран съвет.',
    'faq.q5': 'Мога ли да върна продукт?',
    'faq.a5': 'Да, можете да върнете неотворени продукти в рамките на 14 дни от покупката, съгласно закона за защита на потребителите.',
    'faq.q6': 'Как да създам акаунт?',
    'faq.a6': 'Кликнете на "Регистрация" в горния десен ъгъл и попълнете необходимата информация. Акаунтът ви ще бъде активиран веднага.',
    'faq.q7': 'Доставяте ли извън София?',
    'faq.a7': 'Да, доставяме в цялата страна. Доставката извън София отнема до 24 часа.',
    'faq.q8': 'Сигурни ли са личните ми данни?',
    'faq.a8': 'Да, използваме най-високите стандарти за сигурност и криптиране на данните. Вашата информация е напълно защитена.'
  },
  en: {
    // Header
    'header.title': 'AIPHARM+',
    'header.subtitle': 'AI pharmacy & assistant',
    'header.search': 'Search medicines, vitamins, cosmetics...',
    'header.phone': '+359 2 123 4567',
    'header.freeDelivery': 'Free delivery over €25',
    'header.myProfile': 'My Profile',
    'header.help': 'Help',
    'header.login': 'Login',
    'header.register': 'Register',
    'header.logout': 'Logout',
    'header.settings': 'Profile Settings',
    'header.adminPanel': 'Admin Panel',
    'header.hello': 'Hello',
    'header.administrator': 'Administrator',

    // Navigation
    'navigation.categories': 'Categories',
    'navigation.products': 'Products',

    // Hero Section
    'hero.title': 'AIPHARM+',
    'hero.description': 'Quality medicines with AI consultations and fast delivery',
    'hero.certifiedQuality': 'Certified Quality',
    'hero.support247': '24/7 Support',
    'hero.expressDelivery': 'Express Delivery',
    'hero.qualityAwards': 'Quality Awards',
    'hero.viewProducts': 'View Products',
    'hero.aiAssistant': 'AI Medical Assistant',
    'hero.satisfiedClients': 'Satisfied Clients',
    'hero.productsInStock': 'Products in Stock',
    'hero.professionalCare': 'Professional Care',

    // Categories
    'categories.title': 'Categories',
    'categories.subtitle': 'Explore our main categories and find the right treatments.',
    'categories.previewSubtitle': 'Take a quick look at some of our most popular categories.',
    'categories.viewAll': 'View all categories',
    'categories.viewProducts': 'View products',
    'categories.all': 'All',
    'categories.painkillers': 'Painkillers',
    'categories.vitamins': 'Vitamins',
    'categories.coldFlu': 'Cold & Flu',
    'categories.digestive': 'Digestive',
    'categories.skinHair': 'Skin & Hair',
    'categories.children': 'Children Products',

    // Products
    'products.featuredTitle': 'Featured products',
    'products.featuredSubtitle': 'A quick look at some of our most popular picks.',
    'products.resultsFor': 'Results for',
    'products.category': 'Category',
    'products.unknown': 'Unknown',
    'products.allProducts': 'All Products',
    'products.products': 'products',
    'products.noProducts': 'No products found',
    'products.tryDifferent': 'Try different keywords or browse our categories',
    'products.viewAll': 'View all products',
    'products.showLess': 'Show less',
    'products.prescription': 'Prescription',
    'products.activeIngredient': 'Active Ingredient',
    'products.dosage': 'Dosage',
    'products.manufacturer': 'Manufacturer',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    'products.pieces': 'pcs.',
    'products.add': 'Add',
    'products.catalogTitle': 'Product catalog',
    'products.catalogDescription': 'Browse the full range of medicines, supplements, and cosmetics curated by our specialists.',
    'products.categoryOverview': 'Categories & availability',
    'products.categoryOverviewDescription': 'Quick overview of our main categories and available products.',
    'products.totalProductsLabel': 'Total products',
    'products.inCategory': 'In the category',

    // Cart
    'cart.title': 'Cart',
    'cart.empty': 'Cart is empty',
    'cart.emptyDescription': 'Add products to continue with your order',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'cart.total': 'Total',
    'cart.freeDelivery': '✓ Free delivery',
    'cart.addForFreeDelivery': 'Add products for €{amount} for free delivery',
    'cart.checkout': 'Checkout',

    // AI Assistant
    'ai.title': 'AI Assistant',
    'ai.subtitle': 'Always ready to help',
    'ai.placeholder': 'Ask a question about medicine...',
    'ai.thinking': 'Thinking of an answer...',
    'ai.disclaimer': '⚠️ This is general information. Consult with a doctor.',
    'ai.quickQuestion1': 'How to take paracetamol?',
    'ai.quickQuestion2': 'Ibuprofen side effects?',
    'ai.quickQuestion3': 'Vitamin C dosage?',

    // Auth
    'auth.login': 'Login',
    'auth.loginSubtitle': 'Sign in to your account',
    'auth.register': 'Register',
    'auth.registerSubtitle': 'Create a new account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone',
    'auth.address': 'Address',
    'auth.age': 'Age',
    'auth.gender': 'Gender',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.other': 'Other',
    'auth.rememberMe': 'Remember Me',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.loginButton': 'Sign In',
    'auth.registerButton': 'Register',
    'auth.loggingIn': 'Signing in...',
    'auth.registering': 'Registering...',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.loginHere': 'Sign in here',
    'auth.registerHere': 'Register here',
    'auth.demoAccounts': 'Demo Accounts:',
    'auth.admin': 'Admin',
    'auth.user': 'User',
    'auth.required': 'Required field',
    'auth.passwordsNotMatch': 'Passwords do not match',
    'auth.loginError': 'Login error',
    'auth.registerError': 'Registration error',
    'auth.networkError': 'Network error',
    'auth.loginSuccess': 'Login successful',
    'auth.registerSuccess': 'Registration successful! You can now sign in to your account.',

    // Profile Settings
    'profile.title': 'Profile settings',
    'profile.subtitle': 'Update your contact information and personal details.',
    'profile.email': 'Email address',
    'profile.readonlyEmail': 'The email address cannot be changed.',
    'profile.adminBadge': 'Administrator',
    'profile.fullName': 'Full name',
    'profile.fullNamePlaceholder': 'John Doe',
    'profile.phoneNumber': 'Phone number',
    'profile.phonePlaceholder': '+359 88 123 4567',
    'profile.address': 'Address',
    'profile.addressPlaceholder': 'Sofia, Vitosha Blvd. 25',
    'profile.reset': 'Reset',
    'profile.save': 'Save changes',
    'profile.saving': 'Saving...',
    'profile.success': 'Profile updated successfully.',
    'profile.error': 'Could not update the profile.',
    'profile.notAuthenticated': 'You need to be signed in to edit your profile.',

    // Admin Panel
    'admin.panel.title': 'Administration',
    'admin.panel.subtitle': 'Manage user accounts and permissions',
    'admin.panel.description': 'Review the registered users, edit their details and control access rights.',
    'admin.users.searchLabel': 'Search users',
    'admin.users.searchPlaceholder': 'Name, email or phone...',
    'admin.users.errors.noSession': 'Missing admin session. Please sign in again.',
    'admin.users.errors.fetchFailed': 'Unable to load users.',
    'admin.users.errors.saveFailed': 'Unable to save the changes.',
    'admin.users.retry': 'Try again',
    'admin.users.badges.admin': 'Admin',
    'admin.users.badges.deactivated': 'Deactivated',
    'admin.users.badges.active': 'Active',
    'admin.users.empty': 'No users found.',
    'admin.users.unknownName': 'No name provided',
    'admin.users.memberSince': 'Member since {date}',
    'admin.users.saveSuccess': 'User updated successfully.',
    'admin.users.permissions.title': 'Permissions & status',
    'admin.users.permissions.admin': 'Administrator rights',
    'admin.users.permissions.deactivate': 'Mark as deactivated',
    'admin.users.permissions.selfWarning': 'Warning: you are editing your own account. Do not remove your admin rights unless you are sure.',
    'admin.users.fields.email': 'Email',
    'admin.users.fields.fullName': 'Full name',
    'admin.users.fields.fullNamePlaceholder': 'First and last name',
    'admin.users.fields.phone': 'Phone number',
    'admin.users.fields.phonePlaceholder': 'Contact phone',
    'admin.users.fields.address': 'Address',
    'admin.users.fields.addressPlaceholder': 'Delivery address',
    'admin.users.actions.reset': 'Discard changes',
    'admin.users.actions.refresh': 'Refresh',
    'admin.users.actions.saving': 'Saving...',
    'admin.users.actions.save': 'Save',
    'admin.users.noSelection': 'Select a user from the list to edit their details.',
    // Footer
    'footer.title': 'AIPHARM+',
    'footer.description': 'Quality medicines with AI consultations and fast delivery.',
    'footer.quickLinks': 'Quick Links',
    'footer.aboutUs': 'About Us',
    'footer.products': 'Products',
    'footer.services': 'Services',
    'footer.contacts': 'Contacts',
    'footer.promotions': 'Promotions',
    'footer.faq': 'FAQ',
    'footer.contactsTitle': 'Contact Info',
    'footer.workingHours': 'Working Hours',
    'footer.workingHoursText': 'Mon-Fri: 8:00 - 22:00\nSat-Sun: 9:00 - 20:00',
    'footer.copyright': '© 2024 AIPHARM+. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookies',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.currency': '€',

    // About Us
    'about.description': 'AIPHARM+ is a leading digital pharmacy in Bulgaria, combining traditional pharmaceutical care with the latest AI technologies.',
    'about.mission': 'Our Mission',
    'about.missionText': 'To provide quality medicines and health products with personalized AI consultations, ensuring accessible and reliable healthcare for everyone.',
    'about.vision': 'Our Vision',
    'about.visionText': 'To be the most trusted digital pharmacy in Bulgaria, revolutionizing the way people receive medical advice and medicines.',
    'about.quality': 'Quality',
    'about.qualityText': 'All our products are certified and approved by the Bulgarian Drug Agency.',
    'about.speed': 'Speed',
    'about.speedText': 'Express delivery within 2 hours in Sofia and up to 24 hours nationwide.',
    'about.care': 'Care',
    'about.careText': '24/7 AI assistant and professional pharmacists at your service.',
    'about.clients': 'Satisfied Clients',
    'about.products': 'Products in Stock',
    'about.experience': 'Years Experience',
    'about.support': 'Support',

    // Services
    'services.pageTitle': 'Our services',
    'services.pageDescription': 'We combine digital innovation with professional pharmaceutical care.',
    'services.aiConsultationsTitle': 'AI health consultations',
    'services.aiConsultationsDescription': 'A virtual assistant that provides evidence-based recommendations and tracks your symptoms.',
    'services.aiConsultationsFeature1': 'Personalised medicine recommendations',
    'services.aiConsultationsFeature2': 'Real-time symptom analysis',
    'services.aiConsultationsFeature3': 'Escalation to a pharmacist when needed',
    'services.telepharmacyTitle': 'Telepharmacy experts',
    'services.telepharmacyDescription': 'Licensed pharmacists supporting you remotely.',
    'services.telepharmacyFeature1': 'Video consultations and live chat',
    'services.telepharmacyFeature2': 'Medication interaction checks',
    'services.telepharmacyFeature3': 'Therapy monitoring and follow-up calls',
    'services.deliveryTitle': 'Logistics & delivery',
    'services.deliveryDescription': 'In-house network for fast and safe deliveries nationwide.',
    'services.deliveryFeature1': 'Express two-hour deliveries in Sofia',
    'services.deliveryFeature2': 'Real-time order tracking',
    'services.deliveryFeature3': 'Temperature-controlled transport',
    'services.valueTitle': 'Why choose AIPHARM+',
    'services.valueSubtitle': 'We bring together safety, expertise, and convenience.',
    'services.valuePatients': 'Patient care',
    'services.valuePatientsDesc': 'Individual plans and medicine intake reminders.',
    'services.valueData': 'Data security',
    'services.valueDataDesc': 'Fully encrypted platform with continuous monitoring.',
    'services.valueSupport': '24/7 support',
    'services.valueSupportDesc': 'Specialists available via phone, chat, and email.',
    'services.ctaTitle': 'Need a personal consultation?',
    'services.ctaDescription': 'Contact us and we will guide you to the right service.',
    'services.ctaButton': 'Speak with an expert',

    // Contacts
    'contacts.description': 'Contact us anytime. Our team is ready to help you with all your questions.',
    'contacts.info': 'Contact Information',
    'contacts.phone': 'Phone',
    'contacts.email': 'Email',
    'contacts.address': 'Address',
    'contacts.emergency': 'Emergency Cases',
    'contacts.emergencyText': 'For medical emergencies, please contact emergency services.',
    'contacts.emergencyNumber': 'Emergency Number',
    'contacts.sendMessage': 'Send Message',
    'contacts.firstName': 'First Name',
    'contacts.lastName': 'Last Name',
    'contacts.subject': 'Subject',
    'contacts.message': 'Message',
    'contacts.send': 'Send',
    'contacts.firstNamePlaceholder': 'Your first name',
    'contacts.lastNamePlaceholder': 'Your last name',
    'contacts.emailPlaceholder': 'your@email.com',
    'contacts.subjectPlaceholder': 'Message subject',
    'contacts.messagePlaceholder': 'Write your message here...',

    // Promotions
    'promotions.description': 'Discover our current promotions and save on medicines and health products.',
    'promotions.freeDelivery': 'Free Delivery',
    'promotions.freeDeliveryDesc': 'Free delivery for all orders over €25 nationwide.',
    'promotions.vitamins20': '20% off Vitamins',
    'promotions.vitamins20Desc': 'Special promotion on all vitamins and dietary supplements.',
    'promotions.firstOrder': 'First Order',
    'promotions.firstOrderDesc': '15% discount for new customers on their first order.',
    'promotions.loyaltyProgram': 'Loyalty Program',
    'promotions.loyaltyProgramDesc': 'Collect points with every purchase and get discounts.',
    'promotions.free': 'Free',
    'promotions.points': 'Points',
    'promotions.permanent': 'Permanent',
    'promotions.discount': 'discount',
    'promotions.validUntil': 'Valid until',
    'promotions.useNow': 'Use now',
    'promotions.howToUse': 'How to use promotions',
    'promotions.step1': 'Select products',
    'promotions.step1Desc': 'Add desired products to your cart.',
    'promotions.step2': 'Apply code',
    'promotions.step2Desc': 'Enter promo code at checkout.',
    'promotions.step3': 'Save money',
    'promotions.step3Desc': 'Get the discount and complete your order.',

    // FAQ
    'faq.description': 'Find answers to the most frequently asked questions about our services.',
    'faq.searchPlaceholder': 'Search question...',
    'faq.noResults': 'No results found',
    'faq.tryDifferent': 'Try different keywords.',
    'faq.stillNeedHelp': 'Still need help?',
    'faq.contactSupport': 'Our support team is ready to help you.',
    'faq.callUs': 'Call Us',
    'faq.emailUs': 'Email Us',
    'faq.q1': 'How long does delivery take?',
    'faq.a1': 'Delivery in Sofia takes up to 2 hours, and in the rest of the country - up to 24 hours. For urgent cases, we offer express delivery.',
    'faq.q2': 'What payment methods do you accept?',
    'faq.a2': 'We accept payments with debit and credit cards, bank transfer, as well as cash on delivery.',
    'faq.q3': 'Do I need a prescription for all medicines?',
    'faq.a3': 'No, many medicines are over-the-counter. Products that require a prescription are clearly marked on the site.',
    'faq.q4': 'How does the AI assistant work?',
    'faq.a4': 'Our AI assistant provides general information about medicines. Always consult with a doctor for personalized advice.',
    'faq.q5': 'Can I return a product?',
    'faq.a5': 'Yes, you can return unopened products within 14 days of purchase, according to consumer protection law.',
    'faq.q6': 'How do I create an account?',
    'faq.a6': 'Click "Register" in the top right corner and fill in the required information. Your account will be activated immediately.',
    'faq.q7': 'Do you deliver outside Sofia?',
    'faq.a7': 'Yes, we deliver nationwide. Delivery outside Sofia takes up to 24 hours.',
    'faq.q8': 'Is my personal data safe?',
    'faq.a8': 'Yes, we use the highest standards for data security and encryption. Your information is completely protected.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('bg');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['bg']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};