import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'bg' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  bg: {
    // Header
    'header.title': 'AIPHARM+',
    'header.subtitle': 'AI аптека и асистент',
    'header.search': 'Търсете лекарства, витамини, козметика...',
    'header.phone': '+359 2 123 4567',
    'header.freeDelivery': 'Безплатна доставка над €25',
    'header.myProfile': 'Моят профил',
    'header.help': 'Помощ',
    'header.login': 'Вход',
    'header.register': 'Регистрация',
    'header.logout': 'Изход',
    'header.settings': 'Настройки на профила',
    'header.adminPanel': 'Админ панел',
    'header.hello': 'Здравейте',
    'header.administrator': 'Администратор',

    // Navigation
    'navigation.categories': 'Категории',
    'navigation.products': 'Продукти',

    // Hero Section
    'hero.title': 'AIPHARM+',
    'hero.description': 'Качествени лекарства с AI консултации и бърза доставка',
    'hero.certifiedQuality': 'Сертифицирано качество',
    'hero.support247': '24/7 Поддръжка',
    'hero.expressDelivery': 'Експресна доставка',
    'hero.qualityAwards': 'Награди за качество',
    'hero.viewProducts': 'Разгледайте продуктите',
    'hero.aiAssistant': 'AI Медицински асистент',
    'hero.satisfiedClients': 'Доволни клиенти',
    'hero.productsInStock': 'Продукта в наличност',
    'hero.professionalCare': 'Професионална грижа',

    // Categories
    'categories.title': 'Категории',
    'categories.all': 'Всички',
    'categories.painkillers': 'Обезболяващи',
    'categories.vitamins': 'Витамини',
    'categories.coldFlu': 'Простуда и грип',
    'categories.digestive': 'Стомашно-чревни',
    'categories.skinHair': 'Кожа и коса',
    'categories.children': 'Детски продукти',

    // Products
    'products.featuredTitle': 'Акцентирани продукти',
    'products.featuredSubtitle': 'Показваме селекция от най-търсените ни предложения.',
    'products.resultsFor': 'Резултати за',
    'products.category': 'Категория',
    'products.unknown': 'Неизвестна',
    'products.allProducts': 'Всички продукти',
    'products.products': 'продукта',
    'products.noProducts': 'Няма намерени продукти',
    'products.tryDifferent': 'Опитайте с различни ключови думи или разгледайте нашите категории',
    'products.viewAll': 'Разгледайте всички продукти',
    'products.showLess': 'Покажи по-малко',
    'products.prescription': 'Рецепта',
    'products.activeIngredient': 'Активна съставка',
    'products.dosage': 'Дозировка',
    'products.manufacturer': 'Производител',
    'products.inStock': 'В наличност',
    'products.outOfStock': 'Няма в наличност',
    'products.pieces': 'бр.',
    'products.add': 'Добави',

    // Cart
    'cart.title': 'Количка',
    'cart.empty': 'Количката е празна',
    'cart.emptyDescription': 'Добавете продукти, за да продължите с поръчката',
    'cart.continueShopping': 'Продължете пазаруването',
    'cart.remove': 'Премахни',
    'cart.total': 'Общо',
    'cart.freeDelivery': '✓ Безплатна доставка',
    'cart.addForFreeDelivery': 'Добавете продукти за €{amount} за безплатна доставка',
    'cart.checkout': 'Финализиране на поръчка',

    // AI Assistant
    'ai.title': 'AI Асистент',
    'ai.subtitle': 'Винаги готов да помогне',
    'ai.placeholder': 'Задайте въпрос за лекарство...',
    'ai.thinking': 'Обмислям отговора...',
    'ai.disclaimer': '⚠️ Това е общa информация. Консултирайте се с лекар.',
    'ai.quickQuestion1': 'Как се взима парацетамол?',
    'ai.quickQuestion2': 'Странични ефекти на ибупрофен?',
    'ai.quickQuestion3': 'Витамин C дозировка?',

    // Auth
    'auth.login': 'Вход',
    'auth.loginSubtitle': 'Влезте в профила си',
    'auth.register': 'Регистрация',
    'auth.registerSubtitle': 'Създайте нов акаунт',
    'auth.email': 'Имейл адрес',
    'auth.password': 'Парола',
    'auth.confirmPassword': 'Потвърдете паролата',
    'auth.fullName': 'Пълно име',
    'auth.firstName': 'Име',
    'auth.lastName': 'Фамилия',
    'auth.phone': 'Телефон',
    'auth.address': 'Адрес',
    'auth.age': 'Години',
    'auth.gender': 'Пол',
    'auth.male': 'Мъж',
    'auth.female': 'Жена',
    'auth.other': 'Друг',
    'auth.rememberMe': 'Запомни ме',
    'auth.forgotPassword': 'Забравена парола?',
    'auth.loginButton': 'Влез',
    'auth.registerButton': 'Регистрирай се',
    'auth.loggingIn': 'Влизане...',
    'auth.registering': 'Регистриране...',
    'auth.noAccount': 'Нямате акаунт?',
    'auth.haveAccount': 'Вече имате акаунт?',
    'auth.loginHere': 'Влезте тук',
    'auth.registerHere': 'Регистрирайте се',
    'auth.demoAccounts': 'Демо акаунти:',
    'auth.admin': 'Админ',
    'auth.user': 'Потребител',
    'auth.required': 'Задължително поле',
    'auth.passwordsNotMatch': 'Паролите не съвпадат',
    'auth.loginError': 'Грешка при вход',
    'auth.registerError': 'Грешка при регистрация',
    'auth.networkError': 'Мрежова грешка',
    'auth.loginSuccess': 'Успешен вход',
    'auth.registerSuccess': 'Регистрацията е успешна! Можете да влезете в профила си.',

    // Admin Panel
    'admin.title': 'AI препоръки и екип',
    'admin.subtitle': 'Управлявайте препоръки, продажби и движението на екипа',
    'admin.searchPlaceholder': 'Търсене по име, описания или тагове...',
    'admin.filters.category': 'Категория',
    'admin.filters.status': 'Статус',
    'admin.filters.role': 'Роля',
    'admin.filters.all': 'Всички',
    'admin.filters.reset': 'Изчисти филтрите',
    'admin.metrics.totalTools': 'Общо препоръки',
    'admin.metrics.pending': 'Очакващи препоръки',
    'admin.metrics.active': 'Активни препоръки',
    'admin.metrics.rejected': 'Отхвърлени препоръки',
    'admin.tabs.recommendations': 'Препоръки',
    'admin.tabs.users': 'Потребители',
    'admin.users.metrics.totalUsers': 'Общо потребители',
    'admin.users.metrics.activeUsers': 'Активни потребители',
    'admin.users.metrics.teamSales': 'Обем продажби',
    'admin.users.metrics.averageMonthly': 'Средна месечна продажба',
    'admin.users.metrics.topPerformer': 'Най-силен изпълнител',
    'admin.users.metrics.lastTeamLogin': 'Последно влизане в екипа',
    'admin.users.card.totalSales': 'Кумулативни продажби',
    'admin.users.card.monthlyTarget': 'Месечен таргет',
    'admin.users.card.recentSales': 'Последен месец:',
    'admin.users.card.targetProgress': 'Изпълнение',
    'admin.users.card.lastLogin': 'Последно влизане',
    'admin.users.card.conversionRate': 'Конверсия',
    'admin.users.card.customersServed': 'Обслужени клиенти',
    'admin.users.card.teamShare': 'Дял от екипа',
    'admin.users.card.salesTrend': 'Продажби по месеци',
    'admin.users.card.loginActivity': 'Последни активности',
    'admin.users.card.action.login': 'Вход',
    'admin.users.card.action.logout': 'Изход',
    'admin.status.active': 'Активен',
    'admin.status.pending': 'Очаква одобрение',
    'admin.status.rejected': 'Отхвърлен',
    'admin.status.disabled': 'Спрян временно',
    'admin.actions.approve': 'Одобри',
    'admin.actions.reject': 'Откажи',
    'admin.list.submittedBy': 'Предложено от',
    'admin.list.submittedOn': 'Създадено на',
    'admin.list.lastUpdated': 'Последно обновяване',
    'admin.list.usageCount': 'Брой използвания',
    'admin.list.noResults': 'Няма тулове, които да отговарят на критериите',
    'admin.list.totalLabel': 'Показани тулове:',
    'admin.empty.search': 'Променете филтрите или въведете друга ключова дума.',
    'admin.notes.pending': 'Очаква оценка от администратор.',
    'admin.toast.approved': 'Тулът е одобрен успешно.',
    'admin.toast.rejected': 'Тулът е отхвърлен.',
    'admin.role.admin': 'Администратор',
    'admin.role.pharmacist': 'Фармацевт',
    'admin.role.support': 'Оператор поддръжка',
    'admin.role.doctor': 'Лекар',
    'admin.role.analyst': 'Анализатор',
    'admin.role.manager': 'Мениджър',
    'admin.category.ai': 'AI решения',
    'admin.category.automation': 'Автоматизация',
    'admin.category.analytics': 'Аналитика',
    'admin.category.operations': 'Операции',
    'admin.category.compliance': 'Съответствие',
    'admin.impact.high': 'Високо въздействие',
    'admin.impact.medium': 'Средно въздействие',
    'admin.impact.low': 'Ниско въздействие',

    // Footer
    'footer.title': 'AIPHARM+',
    'footer.description': 'Качествени лекарства с AI консултации и бърза доставка.',
    'footer.quickLinks': 'Бързи връзки',
    'footer.aboutUs': 'За нас',
    'footer.products': 'Продукти',
    'footer.services': 'Услуги',
    'footer.contacts': 'Контакти',
    'footer.promotions': 'Промоции',
    'footer.faq': 'Често задавани въпроси',
    'footer.contactsTitle': 'Контакти',
    'footer.workingHours': 'Работно време',
    'footer.workingHoursText': 'Пон-Пет: 8:00 - 22:00\nСъб-Нед: 9:00 - 20:00',
    'footer.copyright': '© 2024 AIPHARM+. Всички права запазени.',
    'footer.privacy': 'Политика за поверителност',
    'footer.terms': 'Условия за ползване',
    'footer.cookies': 'Бисквитки',

    // Common
    'common.loading': 'Зареждане...',
    'common.error': 'Грешка',
    'common.success': 'Успех',
    'common.cancel': 'Отказ',
    'common.save': 'Запази',
    'common.delete': 'Изтрий',
    'common.edit': 'Редактирай',
    'common.close': 'Затвори',
    'common.back': 'Назад',
    'common.next': 'Напред',
    'common.previous': 'Предишна',
    'common.search': 'Търсене',
    'common.filter': 'Филтър',
    'common.sort': 'Сортиране',
    'common.price': 'Цена',
    'common.quantity': 'Количество',
    'common.total': 'Общо',
    'common.currency': '€',

    // About Us
    'about.description': 'AIPHARM+ е водеща дигитална аптека в България, която съчетава традиционната фармацевтична грижа с най-новите AI технологии.',
    'about.mission': 'Нашата мисия',
    'about.missionText': 'Да предоставяме качествени лекарства и здравни продукти с персонализирани AI консултации, осигурявайки достъпна и надеждна здравна грижа за всеки.',
    'about.vision': 'Нашата визия',
    'about.visionText': 'Да бъдем най-доверената дигитална аптека в България, революционизирайки начина, по който хората получават медицински съвети и лекарства.',
    'about.quality': 'Качество',
    'about.qualityText': 'Всички наши продукти са сертифицирани и одобрени от БЛС.',
    'about.speed': 'Бързина',
    'about.speedText': 'Експресна доставка до 2 часа в София и до 24 часа в цялата страна.',
    'about.care': 'Грижа',
    'about.careText': '24/7 AI асистент и професионални фармацевти на ваше разположение.',
    'about.clients': 'Доволни клиенти',
    'about.products': 'Продукта в наличност',
    'about.experience': 'Години опит',
    'about.support': 'Поддръжка',

    // Contacts
    'contacts.description': 'Свържете се с нас по всяко време. Нашият екип е готов да ви помогне с всички въпроси.',
    'contacts.info': 'Информация за контакт',
    'contacts.phone': 'Телефон',
    'contacts.email': 'Имейл',
    'contacts.address': 'Адрес',
    'contacts.emergency': 'Спешни случаи',
    'contacts.emergencyText': 'При медицински спешни случаи, моля обърнете се към спешните служби.',
    'contacts.emergencyNumber': 'Спешен номер',
    'contacts.sendMessage': 'Изпратете съобщение',
    'contacts.firstName': 'Име',
    'contacts.lastName': 'Фамилия',
    'contacts.subject': 'Тема',
    'contacts.message': 'Съобщение',
    'contacts.send': 'Изпрати',
    'contacts.firstNamePlaceholder': 'Вашето име',
    'contacts.lastNamePlaceholder': 'Вашата фамилия',
    'contacts.emailPlaceholder': 'your@email.com',
    'contacts.subjectPlaceholder': 'Тема на съобщението',
    'contacts.messagePlaceholder': 'Напишете вашето съобщение тук...',

    // Promotions
    'promotions.description': 'Открийте нашите актуални промоции и спестете при покупката на лекарства и здравни продукти.',
    'promotions.freeDelivery': 'Безплатна доставка',
    'promotions.freeDeliveryDesc': 'Безплатна доставка за всички поръчки над €25 в цялата страна.',
    'promotions.vitamins20': '20% отстъпка на витамини',
    'promotions.vitamins20Desc': 'Специална промоция на всички витамини и хранителни добавки.',
    'promotions.firstOrder': 'Първа поръчка',
    'promotions.firstOrderDesc': '15% отстъпка за нови клиенти при първата им поръчка.',
    'promotions.loyaltyProgram': 'Програма за лоялност',
    'promotions.loyaltyProgramDesc': 'Събирайте точки с всяка покупка и получавайте отстъпки.',
    'promotions.free': 'Безплатно',
    'promotions.points': 'Точки',
    'promotions.permanent': 'Постоянна',
    'promotions.discount': 'отстъпка',
    'promotions.validUntil': 'Валидна до',
    'promotions.useNow': 'Използвай сега',
    'promotions.howToUse': 'Как да използвате промоциите',
    'promotions.step1': 'Изберете продукти',
    'promotions.step1Desc': 'Добавете желаните продукти в количката си.',
    'promotions.step2': 'Приложете код',
    'promotions.step2Desc': 'Въведете промо кода при финализиране.',
    'promotions.step3': 'Спестете пари',
    'promotions.step3Desc': 'Получете отстъпката и завършете поръчката.',

    // FAQ
    'faq.description': 'Намерете отговори на най-често задаваните въпроси за нашите услуги.',
    'faq.searchPlaceholder': 'Търсете въпрос...',
    'faq.noResults': 'Няма намерени резултати',
    'faq.tryDifferent': 'Опитайте с различни ключови думи.',
    'faq.stillNeedHelp': 'Все още имате нужда от помощ?',
    'faq.contactSupport': 'Нашият екип за поддръжка е готов да ви помогне.',
    'faq.callUs': 'Обадете се',
    'faq.emailUs': 'Изпратете имейл',
    'faq.q1': 'Колко време отнема доставката?',
    'faq.a1': 'Доставката в София е до 2 часа, а в останалата част на страната - до 24 часа. За спешни случаи предлагаме експресна доставка.',
    'faq.q2': 'Какви методи за плащане приемате?',
    'faq.a2': 'Приемаме плащания с дебитни и кредитни карти, банков превод, както и плащане при доставка (наложен платеж).',
    'faq.q3': 'Нужна ли е рецепта за всички лекарства?',
    'faq.a3': 'Не, много лекарства са безрецептурни. Продуктите, които изискват рецепта, са ясно обозначени в сайта.',
    'faq.q4': 'Как работи AI асистентът?',
    'faq.a4': 'Нашият AI асистент предоставя обща информация за лекарствата. Винаги се консултирайте с лекар за персонализиран съвет.',
    'faq.q5': 'Мога ли да върна продукт?',
    'faq.a5': 'Да, можете да върнете неотворени продукти в рамките на 14 дни от покупката, съгласно закона за защита на потребителите.',
    'faq.q6': 'Как да създам акаунт?',
    'faq.a6': 'Кликнете на "Регистрация" в горния десен ъгъл и попълнете необходимата информация. Акаунтът ви ще бъде активиран веднага.',
    'faq.q7': 'Доставяте ли извън София?',
    'faq.a7': 'Да, доставяме в цялата страна. Доставката извън София отнема до 24 часа.',
    'faq.q8': 'Сигурни ли са личните ми данни?',
    'faq.a8': 'Да, използваме най-високите стандарти за сигурност и криптиране на данните. Вашата информация е напълно защитена.'
  },
  en: {
    // Header
    'header.title': 'AIPHARM+',
    'header.subtitle': 'AI pharmacy & assistant',
    'header.search': 'Search medicines, vitamins, cosmetics...',
    'header.phone': '+359 2 123 4567',
    'header.freeDelivery': 'Free delivery over €25',
    'header.myProfile': 'My Profile',
    'header.help': 'Help',
    'header.login': 'Login',
    'header.register': 'Register',
    'header.logout': 'Logout',
    'header.settings': 'Profile Settings',
    'header.adminPanel': 'Admin Panel',
    'header.hello': 'Hello',
    'header.administrator': 'Administrator',

    // Navigation
    'navigation.categories': 'Categories',
    'navigation.products': 'Products',

    // Hero Section
    'hero.title': 'AIPHARM+',
    'hero.description': 'Quality medicines with AI consultations and fast delivery',
    'hero.certifiedQuality': 'Certified Quality',
    'hero.support247': '24/7 Support',
    'hero.expressDelivery': 'Express Delivery',
    'hero.qualityAwards': 'Quality Awards',
    'hero.viewProducts': 'View Products',
    'hero.aiAssistant': 'AI Medical Assistant',
    'hero.satisfiedClients': 'Satisfied Clients',
    'hero.productsInStock': 'Products in Stock',
    'hero.professionalCare': 'Professional Care',

    // Categories
    'categories.title': 'Categories',
    'categories.all': 'All',
    'categories.painkillers': 'Painkillers',
    'categories.vitamins': 'Vitamins',
    'categories.coldFlu': 'Cold & Flu',
    'categories.digestive': 'Digestive',
    'categories.skinHair': 'Skin & Hair',
    'categories.children': 'Children Products',

    // Products
    'products.featuredTitle': 'Featured products',
    'products.featuredSubtitle': 'A quick look at some of our most popular picks.',
    'products.resultsFor': 'Results for',
    'products.category': 'Category',
    'products.unknown': 'Unknown',
    'products.allProducts': 'All Products',
    'products.products': 'products',
    'products.noProducts': 'No products found',
    'products.tryDifferent': 'Try different keywords or browse our categories',
    'products.viewAll': 'View all products',
    'products.showLess': 'Show less',
    'products.prescription': 'Prescription',
    'products.activeIngredient': 'Active Ingredient',
    'products.dosage': 'Dosage',
    'products.manufacturer': 'Manufacturer',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    'products.pieces': 'pcs.',
    'products.add': 'Add',

    // Cart
    'cart.title': 'Cart',
    'cart.empty': 'Cart is empty',
    'cart.emptyDescription': 'Add products to continue with your order',
    'cart.continueShopping': 'Continue Shopping',
    'cart.remove': 'Remove',
    'cart.total': 'Total',
    'cart.freeDelivery': '✓ Free delivery',
    'cart.addForFreeDelivery': 'Add products for €{amount} for free delivery',
    'cart.checkout': 'Checkout',

    // AI Assistant
    'ai.title': 'AI Assistant',
    'ai.subtitle': 'Always ready to help',
    'ai.placeholder': 'Ask a question about medicine...',
    'ai.thinking': 'Thinking of an answer...',
    'ai.disclaimer': '⚠️ This is general information. Consult with a doctor.',
    'ai.quickQuestion1': 'How to take paracetamol?',
    'ai.quickQuestion2': 'Ibuprofen side effects?',
    'ai.quickQuestion3': 'Vitamin C dosage?',

    // Auth
    'auth.login': 'Login',
    'auth.loginSubtitle': 'Sign in to your account',
    'auth.register': 'Register',
    'auth.registerSubtitle': 'Create a new account',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.fullName': 'Full Name',
    'auth.firstName': 'First Name',
    'auth.lastName': 'Last Name',
    'auth.phone': 'Phone',
    'auth.address': 'Address',
    'auth.age': 'Age',
    'auth.gender': 'Gender',
    'auth.male': 'Male',
    'auth.female': 'Female',
    'auth.other': 'Other',
    'auth.rememberMe': 'Remember Me',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.loginButton': 'Sign In',
    'auth.registerButton': 'Register',
    'auth.loggingIn': 'Signing in...',
    'auth.registering': 'Registering...',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.loginHere': 'Sign in here',
    'auth.registerHere': 'Register here',
    'auth.demoAccounts': 'Demo Accounts:',
    'auth.admin': 'Admin',
    'auth.user': 'User',
    'auth.required': 'Required field',
    'auth.passwordsNotMatch': 'Passwords do not match',
    'auth.loginError': 'Login error',
    'auth.registerError': 'Registration error',
    'auth.networkError': 'Network error',
    'auth.loginSuccess': 'Login successful',
    'auth.registerSuccess': 'Registration successful! You can now sign in to your account.',

    // Admin Panel
    'admin.title': 'AI recommendations & team insights',
    'admin.subtitle': 'Review proposals and follow sales activity across your team',
    'admin.searchPlaceholder': 'Search by name, description or tags...',
    'admin.filters.category': 'Category',
    'admin.filters.status': 'Status',
    'admin.filters.role': 'Role',
    'admin.filters.all': 'All',
    'admin.filters.reset': 'Reset filters',
    'admin.metrics.totalTools': 'Total recommendations',
    'admin.metrics.pending': 'Pending reviews',
    'admin.metrics.active': 'Active recommendations',
    'admin.metrics.rejected': 'Rejected recommendations',
    'admin.tabs.recommendations': 'Recommendations',
    'admin.tabs.users': 'Users & analytics',
    'admin.users.metrics.totalUsers': 'Total users',
    'admin.users.metrics.activeUsers': 'Active users',
    'admin.users.metrics.teamSales': 'Sales volume',
    'admin.users.metrics.averageMonthly': 'Average monthly',
    'admin.users.metrics.topPerformer': 'Top performer',
    'admin.users.metrics.lastTeamLogin': 'Latest team login',
    'admin.users.card.totalSales': 'Cumulative sales',
    'admin.users.card.monthlyTarget': 'Monthly target',
    'admin.users.card.recentSales': 'Last month:',
    'admin.users.card.targetProgress': 'Target achievement',
    'admin.users.card.lastLogin': 'Last login',
    'admin.users.card.conversionRate': 'Conversion rate',
    'admin.users.card.customersServed': 'Customers served',
    'admin.users.card.teamShare': 'Team contribution',
    'admin.users.card.salesTrend': 'Sales trend',
    'admin.users.card.loginActivity': 'Recent activity',
    'admin.users.card.action.login': 'Login',
    'admin.users.card.action.logout': 'Logout',
    'admin.status.active': 'Active',
    'admin.status.pending': 'Awaiting approval',
    'admin.status.rejected': 'Rejected',
    'admin.status.disabled': 'Paused',
    'admin.actions.approve': 'Approve',
    'admin.actions.reject': 'Reject',
    'admin.list.submittedBy': 'Submitted by',
    'admin.list.submittedOn': 'Submitted on',
    'admin.list.lastUpdated': 'Last updated',
    'admin.list.usageCount': 'Usage count',
    'admin.list.noResults': 'No tools match your filters',
    'admin.list.totalLabel': 'Visible tools:',
    'admin.empty.search': 'Try adjusting the filters or search with another keyword.',
    'admin.notes.pending': 'Awaiting review from administrator.',
    'admin.toast.approved': 'Tool approved successfully.',
    'admin.toast.rejected': 'Tool rejected.',
    'admin.role.admin': 'Administrator',
    'admin.role.pharmacist': 'Pharmacist',
    'admin.role.support': 'Support operator',
    'admin.role.doctor': 'Doctor',
    'admin.role.analyst': 'Analyst',
    'admin.role.manager': 'Manager',
    'admin.category.ai': 'AI solutions',
    'admin.category.automation': 'Automation',
    'admin.category.analytics': 'Analytics',
    'admin.category.operations': 'Operations',
    'admin.category.compliance': 'Compliance',
    'admin.impact.high': 'High impact',
    'admin.impact.medium': 'Medium impact',
    'admin.impact.low': 'Low impact',

    // Footer
    'footer.title': 'AIPHARM+',
    'footer.description': 'Quality medicines with AI consultations and fast delivery.',
    'footer.quickLinks': 'Quick Links',
    'footer.aboutUs': 'About Us',
    'footer.products': 'Products',
    'footer.services': 'Services',
    'footer.contacts': 'Contacts',
    'footer.promotions': 'Promotions',
    'footer.faq': 'FAQ',
    'footer.contactsTitle': 'Contact Info',
    'footer.workingHours': 'Working Hours',
    'footer.workingHoursText': 'Mon-Fri: 8:00 - 22:00\nSat-Sun: 9:00 - 20:00',
    'footer.copyright': '© 2024 AIPHARM+. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Use',
    'footer.cookies': 'Cookies',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.currency': '€',

    // About Us
    'about.description': 'AIPHARM+ is a leading digital pharmacy in Bulgaria, combining traditional pharmaceutical care with the latest AI technologies.',
    'about.mission': 'Our Mission',
    'about.missionText': 'To provide quality medicines and health products with personalized AI consultations, ensuring accessible and reliable healthcare for everyone.',
    'about.vision': 'Our Vision',
    'about.visionText': 'To be the most trusted digital pharmacy in Bulgaria, revolutionizing the way people receive medical advice and medicines.',
    'about.quality': 'Quality',
    'about.qualityText': 'All our products are certified and approved by the Bulgarian Drug Agency.',
    'about.speed': 'Speed',
    'about.speedText': 'Express delivery within 2 hours in Sofia and up to 24 hours nationwide.',
    'about.care': 'Care',
    'about.careText': '24/7 AI assistant and professional pharmacists at your service.',
    'about.clients': 'Satisfied Clients',
    'about.products': 'Products in Stock',
    'about.experience': 'Years Experience',
    'about.support': 'Support',

    // Contacts
    'contacts.description': 'Contact us anytime. Our team is ready to help you with all your questions.',
    'contacts.info': 'Contact Information',
    'contacts.phone': 'Phone',
    'contacts.email': 'Email',
    'contacts.address': 'Address',
    'contacts.emergency': 'Emergency Cases',
    'contacts.emergencyText': 'For medical emergencies, please contact emergency services.',
    'contacts.emergencyNumber': 'Emergency Number',
    'contacts.sendMessage': 'Send Message',
    'contacts.firstName': 'First Name',
    'contacts.lastName': 'Last Name',
    'contacts.subject': 'Subject',
    'contacts.message': 'Message',
    'contacts.send': 'Send',
    'contacts.firstNamePlaceholder': 'Your first name',
    'contacts.lastNamePlaceholder': 'Your last name',
    'contacts.emailPlaceholder': 'your@email.com',
    'contacts.subjectPlaceholder': 'Message subject',
    'contacts.messagePlaceholder': 'Write your message here...',

    // Promotions
    'promotions.description': 'Discover our current promotions and save on medicines and health products.',
    'promotions.freeDelivery': 'Free Delivery',
    'promotions.freeDeliveryDesc': 'Free delivery for all orders over €25 nationwide.',
    'promotions.vitamins20': '20% off Vitamins',
    'promotions.vitamins20Desc': 'Special promotion on all vitamins and dietary supplements.',
    'promotions.firstOrder': 'First Order',
    'promotions.firstOrderDesc': '15% discount for new customers on their first order.',
    'promotions.loyaltyProgram': 'Loyalty Program',
    'promotions.loyaltyProgramDesc': 'Collect points with every purchase and get discounts.',
    'promotions.free': 'Free',
    'promotions.points': 'Points',
    'promotions.permanent': 'Permanent',
    'promotions.discount': 'discount',
    'promotions.validUntil': 'Valid until',
    'promotions.useNow': 'Use now',
    'promotions.howToUse': 'How to use promotions',
    'promotions.step1': 'Select products',
    'promotions.step1Desc': 'Add desired products to your cart.',
    'promotions.step2': 'Apply code',
    'promotions.step2Desc': 'Enter promo code at checkout.',
    'promotions.step3': 'Save money',
    'promotions.step3Desc': 'Get the discount and complete your order.',

    // FAQ
    'faq.description': 'Find answers to the most frequently asked questions about our services.',
    'faq.searchPlaceholder': 'Search question...',
    'faq.noResults': 'No results found',
    'faq.tryDifferent': 'Try different keywords.',
    'faq.stillNeedHelp': 'Still need help?',
    'faq.contactSupport': 'Our support team is ready to help you.',
    'faq.callUs': 'Call Us',
    'faq.emailUs': 'Email Us',
    'faq.q1': 'How long does delivery take?',
    'faq.a1': 'Delivery in Sofia takes up to 2 hours, and in the rest of the country - up to 24 hours. For urgent cases, we offer express delivery.',
    'faq.q2': 'What payment methods do you accept?',
    'faq.a2': 'We accept payments with debit and credit cards, bank transfer, as well as cash on delivery.',
    'faq.q3': 'Do I need a prescription for all medicines?',
    'faq.a3': 'No, many medicines are over-the-counter. Products that require a prescription are clearly marked on the site.',
    'faq.q4': 'How does the AI assistant work?',
    'faq.a4': 'Our AI assistant provides general information about medicines. Always consult with a doctor for personalized advice.',
    'faq.q5': 'Can I return a product?',
    'faq.a5': 'Yes, you can return unopened products within 14 days of purchase, according to consumer protection law.',
    'faq.q6': 'How do I create an account?',
    'faq.a6': 'Click "Register" in the top right corner and fill in the required information. Your account will be activated immediately.',
    'faq.q7': 'Do you deliver outside Sofia?',
    'faq.a7': 'Yes, we deliver nationwide. Delivery outside Sofia takes up to 24 hours.',
    'faq.q8': 'Is my personal data safe?',
    'faq.a8': 'Yes, we use the highest standards for data security and encryption. Your information is completely protected.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('bg');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['bg']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};