name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./AIPharm.Backend/AIPharm.sln

      - name: Build
        run: dotnet build ./AIPharm.Backend/AIPharm.sln --no-restore

      - name: Test
        run: dotnet test ./AIPharm.Backend/AIPharm.sln --no-build --verbosity normal

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  docker-build:
    runs-on: ubuntu-latest
    name: Docker Build Test
    needs: [backend-tests, frontend-tests]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker compose build

      - name: Run Docker containers
        run: docker compose up -d

      - name: Wait for services
        run: sleep 30

      - name: Test frontend health
        run: curl -f http://localhost:3000 || exit 1

      - name: Test backend health
        run: curl -f http://localhost:5000/health || exit 1

      - name: Stop containers
        run: docker compose down
